IMAGE_SIZE: [256, 256]
MODEL:
  SAVE_STEP: 3000
  AVGPOOL_ENCODING: True

SOLVER:
  MAX_ITER: 10000
  LR: 0.1
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-7

ENCODER:
  CNV_OUT_CHANNELS: [300, 3]

DECODER:
  CNV_OUT_CHANNELS: [300, 3]

LOG_STEP: 500
BATCH_SIZE: 16
DATASET_NAME: "voc"

OUTPUT_DIR: "autoencoder_outputs/2_layers_lr_02_256to3_256x256_mse"