IMAGE_SIZE: [300, 300]
DOWNSAMPLE: False
MODEL:
  SAVE_STEP: 4000
  AVGPOOL_ENCODING: True
  AVG_POOL_COUNT: 0
  MODEL_NAME: "gan_object_detector"
  QUANTIZE: False
  C: 3
  f: [100, 100, 100, 100]


SOLVER:
  MAX_ITER: 10000
  LR: 0.005
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-7
  DISTORTION_PENALTY_FACTOR: 0.0
  PERFORMANCE_DEGRADATION_FACTOR: 3
  TARGET_LOSS_FACTOR: 20
  HINGE_LOSS_THRESHOLD: 100000
  CHI: 2.01
  TARGET_CLASS: 0
  DISCRIMINATOR_IMPORTANCE: 20.
  TARGET_SENSITIVITY: 5e4
  ITERATIONS_PER_IMAGE: 15

ENCODER:
  CNV_OUT_CHANNELS: [300, 1]

DECODER:
  CNV_OUT_CHANNELS: [300, 1]

LOG_STEP: 1
BATCH_SIZE: 1

DATASET_NAME: "voc_detection"
MODEL_SAVE_STEP: 100
DRAW_STEP: 1
OUTPUT_DIR: "autoencoder_outputs/gan_attacker_05"
DRAW_TO_DIR: "gan_attacker_05"