IMAGE_SIZE: [300, 300]
MODEL:
  SAVE_STEP: 3000
  AVGPOOL_ENCODING: True
  AVG_POOL_COUNT: 0
  MODEL_NAME: "gan_object_detector"
  QUANTIZE: False
  C: 8
  f: [60, 120, 240, 480, 960]


SOLVER:
  MAX_ITER: 10000
  LR: 0.00018
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-7
  DISTORTION_PENALTY_FACTOR: 0
  PERFORMANCE_DEGRADATION_FACTOR: 0
  TARGET_LOSS_FACTOR: 3
  HINGE_LOSS_THRESHOLD: 200
  HINGE_LOSS_FACTOR: 1
  CHI: 2
  TARGET_CLASS: 0

ENCODER:
  CNV_OUT_CHANNELS: [300, 1]

DECODER:
  CNV_OUT_CHANNELS: [300, 1]

LOG_STEP: 500
BATCH_SIZE: 2

DATASET_NAME: "voc_detection"
MODEL_SAVE_STEP: 100
DRAW_STEP: 1
OUTPUT_DIR: "autoencoder_outputs/gan69"
DRAW_TO_DIR: "gan69_out"