IMAGE_SIZE: [300, 300]
MODEL:
  SAVE_STEP: 500
  AVGPOOL_ENCODING: True
  AVG_POOL_COUNT: 0
  MODEL_NAME: "gan_object_detector"
  QUANTIZE: False
  C: 8


SOLVER:
  MAX_ITER: 10000
  LR: 0.00018
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-7
  DISTORTION_PENALTY_FACTOR: 5
  PERFORMANCE_DEGRADATION_FACTOR: 0
  TARGET_LOSS_FACTOR: 15
  HINGE_LOSS_THRESHOLD: 200
  HINGE_LOSS_FACTOR: 1
  CHI: 2.01
  TARGET_CLASS: 10
  ITERATIONS_PER_IMAGE: 100

ENCODER:
  CNV_OUT_CHANNELS: [300, 1]

DECODER:
  CNV_OUT_CHANNELS: [300, 1]

LOG_STEP: 500
BATCH_SIZE: 1

DATASET_NAME: "voc_detection"
MODEL_SAVE_STEP: 100
DRAW_STEP: 1
OUTPUT_DIR: "autoencoder_outputs/gan70"
DRAW_TO_DIR: "gan70_out"