IMAGE_SIZE: [300, 300]
DOWNSAMPLE: True
MODEL:
  SAVE_STEP: 5000
  EVAL_STEP: 20000
  AVGPOOL_ENCODING: True
  AVG_POOL_COUNT: 0
  MODEL_NAME: "gan_object_detector"
  QUANTIZE: False
  D_F: [100, 200, 300, 400, 500, 600, 1200]
  C: 64

SOLVER:
  MAX_ITER: 10000
  LR: 0.00014
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-7
  DISTORTION_PENALTY_FACTOR: 0.0001
  DISCRIMINATOR_IMPORTANCE: 20.
  DISC_REC_IMPORTANCE: 10.
  PERFORMANCE_DEGRADATION_FACTOR: 0
  TARGET_LOSS_FACTOR: 20
  HINGE_LOSS_THRESHOLD: 50000
  CHI: 2.01
  TARGET_CLASS: 0
  ITERATIONS_PER_IMAGE: 1

ENCODER:
  CNV_OUT_CHANNELS: [300, 1]

DECODER:
  CNV_OUT_CHANNELS: [300, 1]

BATCH_SIZE: 2

DATASET_NAME: "voc_detection"
MODEL_SAVE_STEP: 100
DRAW_STEP: 20
OUTPUT_DIR: "autoencoder_outputs/gan_attacker_04_downsample_10"
DRAW_TO_DIR: "gan_attacker_04_downsample_10"