IMAGE_SIZE: [300, 300]
MODEL:
  SAVE_STEP: 20000
  AVGPOOL_ENCODING: True
  AVG_POOL_COUNT: 0
  MODEL_NAME: "gan_object_detector"
  QUANTIZE: True
  C: 1

SOLVER:
  MAX_ITER: 10000
  LR: 0.00025
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-7
  DISTORTION_PENALTY_FACTOR: 0
  PERFORMANCE_DEGRADATION_FACTOR: 10
  HINGE_LOSS_THRESHOLD: 100
  HINGE_LOSS_FACTOR: 8

ENCODER:
  CNV_OUT_CHANNELS: [300, 1]

DECODER:
  CNV_OUT_CHANNELS: [300, 1]

LOG_STEP: 500
BATCH_SIZE: 2

DATASET_NAME: "voc_detection"
MODEL_SAVE_STEP: 100
DRAW_STEP: 100
OUTPUT_DIR: "autoencoder_outputs/gan50"
DRAW_TO_DIR: "gan50_out"