IMAGE_SIZE: [256, 256]
MODEL:
  SAVE_STEP: 400
  AVGPOOL_ENCODING: True
  AVG_POOL_COUNT: 0

SOLVER:
  MAX_ITER: 10000
  LR: 0.0002
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-7

ENCODER:
  CNV_OUT_CHANNELS: [300, 1]

DECODER:
  CNV_OUT_CHANNELS: [300, 1]

LOG_STEP: 500
BATCH_SIZE: 16
DATASET_NAME: "voc"
MODEL_SAVE_STEP: 400
OUTPUT_DIR: "autoencoder_outputs/gan1"