IMAGE_SIZE: [300, 300]
DOWNSAMPLE: False
MODEL:
  SAVE_STEP: 4000
  AVGPOOL_ENCODING: True
  AVG_POOL_COUNT: 0
  MODEL_NAME: "gan_object_detector"
  QUANTIZE: False
  C: 3
  f: [100, 100, 100, 100, 100, 256, 512, 960]


SOLVER:
  MAX_ITER: 10000
  LR: 0.0002
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-7
  DISTORTION_PENALTY_FACTOR: 0.005
  PERFORMANCE_DEGRADATION_FACTOR: 0
  TARGET_LOSS_FACTOR: 20
  HINGE_LOSS_THRESHOLD: 2000
  CHI: 2.01
  TARGET_CLASS: 0
  ITERATIONS_PER_IMAGE: 1

ENCODER:
  CNV_OUT_CHANNELS: [300, 1]

DECODER:
  CNV_OUT_CHANNELS: [300, 1]

BATCH_SIZE: 1

DATASET_NAME: "voc_detection"
MODEL_SAVE_STEP: 100
DRAW_STEP: 50
OUTPUT_DIR: "autoencoder_outputs/gan_attacker_01_130"
DRAW_TO_DIR: "gan_attacker_01_130"