IMAGE_SIZE: [256, 256]
MODEL:
  SAVE_STEP: 500
  AVGPOOL_ENCODING: True
  AVG_POOL_COUNT: 0

SOLVER:
  MAX_ITER: 10000
  LR: 0.1
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-8

ENCODER:
  CNV_OUT_CHANNELS: [500, 1000, 1500, 2000, 2200, 3]

DECODER:
  CNV_OUT_CHANNELS: [2200, 2000, 1500, 1000, 500, 3]

LOG_STEP: 300
BATCH_SIZE: 4
DATASET_NAME: "voc"

OUTPUT_DIR: "autoencoder_outputs/6_layers_HUGE_256to3_256x256_mse"
