IMAGE_SIZE: [256, 256]
MODEL:
  SAVE_STEP: 5
ENCODER:
  CNV_OUT_CHANNELS: [256, 3]

DECODER:
  CNV_OUT_CHANNELS: [256, 3]

SOLVER:
  MAX_ITER: 10000
  LR: 0.2
  WHICH_OPTIMIZER: "SGD"

LOG_STEP: 10
BATCH_SIZE: 1
DATASET_NAME: "test"
OUTPUT_DIR: "autoencoder_outputs/test"