IMAGE_SIZE: [300, 300]
MODEL:
  SAVE_STEP: 1000
  AVGPOOL_ENCODING: True
  AVG_POOL_COUNT: 0

SOLVER:
  MAX_ITER: 10000
  LR: 0.1
  WHICH_OPTIMIZER: "SGD"
  LOSS_FUNCTION: "MSE"
  L1_REGULARIZATION_FACTOR: 1e-7

ENCODER:
  CNV_OUT_CHANNELS: [300, 1]

DECODER:
  CNV_OUT_CHANNELS: [300, 1]

LOG_STEP: 10
BATCH_SIZE: 1
DATASET_NAME: "voc"

OUTPUT_DIR: "autoencoder_outputs/1layer300x300"