_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/fcrnn_x101_fpn_coco.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20

DATASETS:
  TRAIN: ('voc_2012_trainval',)
  TEST: ('voc_2012_test',)

SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 50000
