MODEL:
    NUM_CLASSES: 11
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [16, 16, 16, 16, 16, 16]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("mnist_detection_train", "mnist_detection_val")
    TEST: ("mnist_detection_val", )
SOLVER:
    MAX_ITER: 1000
    GAMMA: 0.1
    BATCH_SIZE: 1
    LR: 2e-3
OUTPUT_DIR: 'outputs/basic'
