MODEL:
  NUM_CLASSES: 21
  DEVICE: "cpu"
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2012_train", )
  TEST: ("voc_2012_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/ssd300'