MODEL:
  NUM_CLASSES: 21

  BOX_HEAD:
    PREDICTOR: 'SSDLiteBoxPredictor'
  BACKBONE:
    NAME: 'mobilenet_v3'
    OUT_CHANNELS: (112, 960, 512, 256, 256)
  PRIORS:
    FEATURE_MAPS: [16, 8, 4, 2, 1]
    STRIDES: [16, 32, 64, 178, 256]
    MIN_SIZES: [60, 105, 150, 195, 240]
    MAX_SIZES: [105, 150, 195, 240, 285]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3]]
    BOXES_PER_LOCATION: [6, 6, 6, 6, 6]
INPUT:
  IMAGE_SIZE: 256
DATASETS:
  TRAIN: ("voc_2012_train", )
  TEST: ("voc_2012_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'detector_outputs/voc_mobilenet_test'
