from yacs.config import CfgNode as CN

cfg = CN()
cfg.OUTPUT_DIR = "ppo_atk_outputs"
cfg.OUTPUT_FILE = "ppo1.zip"
cfg.DRAW_DIR = "justtosee"
cfg.REWARD = CN()
cfg.REWARD.DELTA_FACTOR = 0.001
cfg.REWARD.PERFORMANCE_REDUCTION_FACTOR = 2
cfg.REWARD.CLS_REWARD_REDUCTION_FACTOR = 1
cfg.REWARD.PIXELS_REMOVED_FACTOR = 1
cfg.REWARD.END_PIXEL_BONUS_FACTOR = 1
cfg.REWARD.BOXES_PLACED_FACTOR = 0.1
cfg.REWARD.BOX_ENCOURAGEMENT_FACTOR = 100
cfg.DONE_THRESHOLD = 0.1
cfg.TRAIN = CN()
cfg.TRAIN.MAX_EPISODES= 10000
cfg.TRAIN.SAVE_STEP = 15000
cfg.TRAIN.SAVE_AMOUNT = 1000