REWARD:
  BOXES_PLACED_FACTOR: 0.1
  PERFORMANCE_REDUCTION_FACTOR: 2.
  PIXELS_REMOVED_FACTOR: 5.
  END_PIXEL_BONUS_FACTOR: 15.
  CLS_REWARD_REDUCTION_FACTOR: 6.

DRAW_DIR: "rl_images3"
OUTPUT_DIR: "ppo_atk_outputs"
OUTPUT_FILE: "ppo3.zip"