REWARD:
  BOXES_PLACED_FACTOR: 2
  PERFORMANCE_REDUCTION_FACTOR: 2
  PIXELS_REMOVED_FACTOR: 1
  END_PIXEL_BONUS_FACTOR: 1
  CLS_REWARD_REDUCTION_FACTOR: 6

DRAW_DIR: "rl_images2"
OUTPUT_DIR: "ppo_atk_outputs"
OUTPUT_FILE: "ppo2.zip"