REWARD:
  BOXES_PLACED_FACTOR: 10
  PERFORMANCE_REDUCTION_FACTOR: 2
  PIXELS_REMOVED_FACTOR: 2
  END_PIXEL_BONUS_FACTOR: 1
  CLS_REWARD_REDUCTION_FACTOR: 1

DRAW_DIR: "rl_images4"
OUTPUT_DIR: "ppo_atk_outputs"
OUTPUT_FILE: "ppo4.zip"