REWARD:
  BOXES_PLACED_FACTOR: 0.1
  PERFORMANCE_REDUCTION_FACTOR: 2
  PIXELS_REMOVED_FACTOR: 3
  END_PIXEL_BONUS_FACTOR: 5
  CLS_REWARD_REDUCTION_FACTOR: 5

DRAW_DIR: "rl_images1"
OUTPUT_DIR: "ppo_atk_outputs"
OUTPUT_FILE: "ppo1.zip"