IMAGE_SIZE: [256, 256]
ENCODER:
  CNV_OUT_CHANNELS: [256, 3]

DECODER:
  CNV_OUT_CHANNELS: [256, 3]

SOLVER:
  MAX_ITER: 10000
  LR: 0.2
  WHICH_OPTIMIZER: "SGD"

LOG_STEP: 500
BATCH_SIZE: 16
DATASET_NAME: "voc"

OUTPUT_DIR: "autoencoder_outputs/2_layers_lr_02_256to3_256x256"